Snowball_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: BVYSPGU-CN80718
      user: RR123
      password: Zxcvbnm@600113
      role: ACCOUNTADMIN
      database: arr_sandbox
      warehouse: compute_wh
      schema: dbo
      threads: 4
      client_session_keep_alive: False